"""Domain exceptions for Analysis Service."""

from .domain_exceptions import (
    DomainException,
    DocumentException,
    DocumentNotFoundException,
    DocumentValidationException,
    DocumentSizeExceededException,
    AnalysisException,
    AnalysisNotFoundException,
    AnalysisExecutionException,
    AnalysisTimeoutException,
    AnalysisAlreadyRunningException,
    FindingException,
    FindingNotFoundException,
    FindingAlreadyResolvedException,
    RepositoryException,
    RepositoryNotFoundException,
    RepositoryConnectionException,
    RepositorySyncException,
    ExternalServiceException,
    SemanticAnalysisException,
    SentimentAnalysisException,
    ConfigurationException,
    AuthorizationException,
    ResourceLimitExceededException,
    ValidationException,
    BusinessRuleViolation
)

__all__ = [
    'DomainException',
    'DocumentException',
    'DocumentNotFoundException',
    'DocumentValidationException',
    'DocumentSizeExceededException',
    'AnalysisException',
    'AnalysisNotFoundException',
    'AnalysisExecutionException',
    'AnalysisTimeoutException',
    'AnalysisAlreadyRunningException',
    'FindingException',
    'FindingNotFoundException',
    'FindingAlreadyResolvedException',
    'RepositoryException',
    'RepositoryNotFoundException',
    'RepositoryConnectionException',
    'RepositorySyncException',
    'ExternalServiceException',
    'SemanticAnalysisException',
    'SentimentAnalysisException',
    'ConfigurationException',
    'AuthorizationException',
    'ResourceLimitExceededException',
    'ValidationException',
    'BusinessRuleViolation'
]
